version: "3"
services:
  app:
    build: .
    tty: true
    ports:
      - "5001:5001"
    container_name: app
    volumes:
      - .:/app
    depends_on:
      - db
  db:
    image: postgres:15.2
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: prevc
      TZ: "Asia/Tokyo"
    # volumes:
      # - ./eng-data:/var/lib/postgresql/data